######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 18 10:21:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .
CONFIG -= qt
unix:LIBS += -lsfml-graphics -lsfml-window -lsfml-system

OBJECTS_DIR = obj

# Input
HEADERS += src/*.h
SOURCES += src/*.cpp
